services:
  mcscale:
    build: .
    image: msscale:1.0v
    restart: always
    volumes:
      - .:/home/admin/mcscale
    working_dir: /home/admin/mcscale
    env_file:
      - .env
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"
      - "/dev/ttyUSB2:/dev/ttyUSB2"
