services:
  mcscale:
    #  build: .
    image: mochigome/mcscale:1.0v
    restart: always
    volumes:
      - .:/home/admin/mcscale
    working_dir: /home/admin/mcscale
    env_file:
      - .env
    devices:
      - "${USB0}:/dev/ttyUSB0"
      - "${USB1}:/dev/ttyUSB1"
      - "${USB2}:/dev/ttyUSB2"

# docker compose -f docker-compose-production.yml logs -f
