services:
  mcscale:
    image: python:3.9
    restart: always
    volumes:
      - .:/home/admin/mcscale
    working_dir: /home/admin/mcscale
    command: bash -c "pip install pymcprotocol && pip install pyserial && python -u main.py"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"
      - "/dev/ttyUSB2:/dev/ttyUSB2"