services:
  mcscale:
    build: .
    image: msscale:1.0v
    restart: always
    volumes:
      - .:/home/admin/mcscale
    working_dir: /home/admin/mcscale
    env_file:
      - .env
    devices:
      - "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B002TCY0-if00-port0:/dev/ttyUSB0"
      - "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B002T0XP-if00-port0:/dev/ttyUSB1"
      - "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B002T0PJ-if00-port0:/dev/ttyUSB2"
